// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tiktok/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/login/email",
					Handler: LoginWithEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/login/phone",
					Handler: LoginWithPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/login/username",
					Handler: LoginWithUsernameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/register",
					Handler: RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/upload/image",
					Handler: UploadImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware, serverCtx.AuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/upload",
					Handler: UserUploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
