// Code generated by goctl. DO NOT EDIT.
package types

type LiveListResp struct {
	UserList []User `json:"user_list"`
}

type StartResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	StreamUrl  string `json:"stream_url"`
}

type User struct {
	UId          int64  `json:"uid"`
	Name         string `json:"name"`
	Avatar       string `json:"avatar"`
	Signature    string `json:"signature"`
	IsFollow     bool   `json:"is_follow"`
	LiveCoverUrl string `json:"live_cover_url"`
	LiveUrl      string `json:"live_url"`
}
