// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tiktok/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/danmu/listv3",
					Handler: DanmuActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/danmu/listv3",
					Handler: GetDanmuListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware, serverCtx.AuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/comment/action",
					Handler: CommentActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/comment/list",
					Handler: GetCommentListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
