// Code generated by goctl. DO NOT EDIT!

package danmumodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"tiktok/common/globalkey"
)

var (
	danmuFieldNames          = builder.RawFieldNames(&Danmu{})
	danmuRows                = strings.Join(danmuFieldNames, ",")
	danmuRowsExpectAutoSet   = strings.Join(stringx.Remove(danmuFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	danmuRowsWithPlaceHolder = strings.Join(stringx.Remove(danmuFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheTiktokDanmuIdPrefix = "cache:tiktok:danmu:id:"
)

type (
	danmuModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Danmu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Danmu, error)
		Update(ctx context.Context, session sqlx.Session, data *Danmu) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Danmu) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Danmu) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Danmu, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Danmu, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Danmu, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Danmu, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Danmu, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultDanmuModel struct {
		sqlc.CachedConn
		table string
	}

	Danmu struct {
		Id         int64     `db:"id"`      // 主键
		Uid        int64     `db:"uid"`     // 用户id
		Vid        int64     `db:"vid"`     // 视频Id
		Content    string    `db:"content"` // 评论内容
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`   // 版本号
		SendTime   float64   `db:"send_time"` // 在视频的哪个点发送的弹幕
	}
)

func newDanmuModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultDanmuModel {
	return &defaultDanmuModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`danmu`",
	}
}

func (m *defaultDanmuModel) Insert(ctx context.Context, session sqlx.Session, data *Danmu) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	tiktokDanmuIdKey := fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, danmuRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime)
	}, tiktokDanmuIdKey)
}

func (m *defaultDanmuModel) FindOne(ctx context.Context, id int64) (*Danmu, error) {
	tiktokDanmuIdKey := fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, id)
	var resp Danmu
	err := m.QueryRowCtx(ctx, &resp, tiktokDanmuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", danmuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDanmuModel) Update(ctx context.Context, session sqlx.Session, data *Danmu) (sql.Result, error) {
	tiktokDanmuIdKey := fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, danmuRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime, data.Id)
	}, tiktokDanmuIdKey)
}

func (m *defaultDanmuModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Danmu) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "DanmuModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultDanmuModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultDanmuModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultDanmuModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Danmu, error) {

	builder = builder.Columns(danmuRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Danmu
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDanmuModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Danmu, error) {

	builder = builder.Columns(danmuRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Danmu
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDanmuModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Danmu, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(danmuRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Danmu
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultDanmuModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Danmu, error) {

	builder = builder.Columns(danmuRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Danmu
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDanmuModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Danmu, error) {

	builder = builder.Columns(danmuRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Danmu
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDanmuModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultDanmuModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultDanmuModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Danmu) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	tiktokDanmuIdKey := fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, danmuRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.Uid, data.Vid, data.Content, data.DeleteTime, data.DelState, data.Version, data.SendTime, data.Id, oldVersion)
	}, tiktokDanmuIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}
func (m *defaultDanmuModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	tiktokDanmuIdKey := fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, tiktokDanmuIdKey)
	return err
}
func (m *defaultDanmuModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTiktokDanmuIdPrefix, primary)
}
func (m *defaultDanmuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", danmuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultDanmuModel) tableName() string {
	return m.table
}
