// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tiktok/live/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware, serverCtx.AuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/live/list",
					Handler: LiveListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/live/start",
					Handler: StartHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
