// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tiktok/relation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SetContextInfoMidlleware, serverCtx.AuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/relation/action",
					Handler: FavoriteActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/favoriteList",
					Handler: FavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/followerList",
					Handler: FollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/friendList",
					Handler: FriendListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
